name: liushui_app
description: "liushui_app"
publish_to: "none"

version: 0.0.2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  easy_refresh: ^3.4.0
  fluttertoast: ^8.2.10
  flutter_svg: ^2.0.16

  dio: ^5.0.0
  retrofit: ^4.4.2
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_db_store: ^6.0.0
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2

  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.0.15
  path: ^1.8.3
  package_info_plus: ^8.3.0

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  logger: ^2.5.0
  crypto: ^3.0.6
  uuid: ^4.3.3
  synchronized: ^3.1.0+1
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  flutter_quill: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 代码生成
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9
  hive_ce_generator: ^1.8.0
  freezed: ^2.4.7

  analyzer: ^7.3.0
  flutter_launcher_icons: ^0.14.2
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

dependency_overrides:
  quill_native_bridge_windows: 0.0.1

# 应用图标配置
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"
  # 运行命令: dart run flutter_launcher_icons

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    # - assets/icons/
    # - assets/fonts/

  # 字体配置
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
